apiVersion: v1
kind: Pod
metadata:
  name: ssh
  labels:
    app: ssh
spec:
  containers:
  - image: tviveiros/ssh:1.1
    name: ssh
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 250m
        memory: 256Mi